apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-config
data:
  CONTEXTO: /home/ubuntu/Caronte
  AUTOR: dennisalro
  TZ: Europe/Madrid
  PROYECTO: Pokeapi
  GITHUB: https://github.com/DennisAlRo/reactasir.git
  USUARIO: dennialro
  PASSWD: Eradedalt1
  HOSTNAME: react
  PORT_SSH: "45678"
  PORT_ORIGEN: "8083"