apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-kube
  namespace: default
spec:
  replicas: 1 # Número de réplicas
  selector:
    matchLabels:
      app: pokeapi-kube
  template:
    metadata:
      labels:
        app: pokeapi-kube
    spec:
      containers:
        - name: pokeapi-kube
          image: dennisalro/pokeapi
          env:
            - name: USUARIO
              value: "dennisalro"
            - name: PROYECTO
              value: "reactasir"
            - name: GITHUB
              value: "https://github.com/DennisAlRo/reactasir.git"